appname = Xchango_APIS_CRUD
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:0219251007@127.0.0.1:5432/xchango_db?sslmode=disable&search_path=sistema
