appname = Xchango_APIS_CRUD
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1:5432/Xchango_db?sslmode=disable&search_path=Usuario_seguridad
